import React from 'react'
import { useParams } from 'react-router-dom';
import Reviews from './Reviews';
import {BiDislike, BiLike} from 'react-icons/bi'
import { BsChatDots } from 'react-icons/bs'

export default function WorkerExp() {
    const { workerId } = useParams();
    const dis = "Je suis un plombier hautement qualifié avec de nombreuses années d'expérience dans le domaine. Je suis passionné par mon métier et j'ai une connaissance approfondie des systèmes de plomberie, des outils et des techniques les plus avancées. Mon expertise me permet de résoudre rapidement et efficacement les problèmes de plomberie les plus complexes, et j'ai une grande fierté à offrir un service exceptionnel à mes clients. En tant que plombier professionnel, je m'engage à travailler avec diligence, à respecter les normes de sécurité les plus strictes, et à fournir un service de qualité supérieure à chaque fois"
    const khedama = [  
      {key: 1,name: "Youssef Jbar",pro: true,description: "En tant qu'électricien, mon travail consiste à installer, réparer et entretenir des systèmes électriques en toute sécurité. Je suis responsable de l'installation de nouveaux systèmes, de la réparation et de l'entretien des systèmes existants, ainsi que de la résolution de problèmes électriques. Je travaille avec des outils et des équipements spécialisés et je collabore étroitement avec les clients et les autres professionnels de la construction.",rating: 123, star: 5,price: 444, job: " électricien ",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104424489174970418/image.png",workImage: "",city: "Casablanca", gendre: "Male"},
      {key: 2,name: "Mohammed Hassan",pro: false,description: "En tant que plombier, je suis chargé d'installer, réparer et entretenir les systèmes de plomberie dans les bâtiments résidentiels, commerciaux et industriels. Je dois avoir une connaissance approfondie des principes de la plomberie et des normes de sécurité pour travailler efficacement et en toute sécurité avec les équipements de plomberie. Je suis également responsable de diagnostiquer les problèmes de plomberie et de trouver des solutions efficaces pour les résoudre. Je travaille avec des outils et des équipements spécialisés et je collabore étroitement avec les clients et les autres professionnels de la construction pour assurer un travail de qualité.",rating: 76, star: 4,price: 300, job: "Plombier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104425155838619859/image.png",workImage: "",city: "Marrakech", gendre: "Male"},
      {key: 3,name: "Abdelkader Ali",pro: false,description: "En tant que menuisier, je suis chargé de fabriquer, réparer et installer des éléments en bois pour les bâtiments résidentiels, commerciaux et industriels. Je dois avoir une connaissance approfondie des différentes techniques de menuiserie et des outils spécialisés nécessaires pour effectuer ces tâches. Je suis également responsable de la réparation et de l'entretien des éléments en bois existants, comme les portes et les fenêtres. Je travaille en étroite collaboration avec les clients et les autres professionnels de la construction pour fournir un travail de qualité, tout en veillant à travailler en toute sécurité avec des outils électriques et des équipements potentiellement dangereux.",rating: 95, star: 4,price: 350, job: "Menuisier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104425318539874345/image.png",workImage: "",city: "Rabat", gendre: "Male"},
      {key: 4,name: "Nadia Bouchra",pro: false,description: "En tant que peintre en bâtiment, mon travail consiste à préparer et à peindre les surfaces intérieures et extérieures des bâtiments résidentiels, commerciaux et industriels. Je suis responsable de la préparation des surfaces avant la peinture, la réparation des surfaces endommagées, la protection des surfaces environnantes et le nettoyage du site après les travaux. Je travaille en étroite collaboration avec les clients et les autres professionnels de la construction pour répondre à leurs besoins en matière de couleurs et de finitions, tout en veillant à travailler en toute sécurité avec des outils électriques et sur des échelles.",rating: 82, star: 4,price: 400, job: "Peintre en bâtiment",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104425871294603376/image.png",workImage: "",city: "Tangier", gendre: "Female"},
      {key: 5,name: "Ali Ben Ahmed",pro: false,description: "En tant que maçon, je suis responsable de la construction, de la réparation et de l'entretien de structures en maçonnerie telles que des murs, des fondations, des dalles et des cheminées. Je dois avoir une connaissance approfondie des différentes techniques de maçonnerie et des matériaux utilisés pour effectuer ces tâches. Je travaille en étroite collaboration avec les clients et les autres professionnels de la construction pour fournir un travail de qualité, tout en veillant à travailler en toute sécurité avec des outils électriques et des équipements potentiellement dangereux. Je suis également responsable de la mesure, de la coupe et de la pose des matériaux, ainsi que de la préparation et du nettoyage du site de travail. La précision, la créativité et la capacité à travailler en équipe sont des compétences clés pour réussir en tant que maçon.",rating: 67, star: 3,price: 250, job: "Maçon",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104424411248988230/image.png",workImage: "",city: "Meknès", gendre: "Male"},
      {key: 6,name: "Fatima Zahra",pro: false,description: "En tant que couvreur, mon travail consiste à installer, réparer et entretenir les toits des bâtiments. Je dois avoir une connaissance approfondie des différents matériaux de toiture tels que les tuiles, les bardeaux, les ardoises et les métaux pour effectuer ces tâches. Je suis responsable de la mesure, de la coupe et de la pose des matériaux de toiture, ainsi que de l'installation des gouttières et des systèmes de drainage pour assurer la protection de la structure du bâtiment contre les intempéries. Je travaille en étroite collaboration avec les clients et les autres professionnels de la construction pour fournir un travail de qualité, tout en veillant à travailler en toute sécurité avec des outils électriques et des équipements potentiellement dangereux. La capacité à travailler en hauteur et la connaissance des normes de sécurité sont des compétences clés pour réussir en tant que couvreur.",rating: 0, star: 0,price: 200, job: "Couvreur",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104426458794950838/image.png",workImage: "",city: "El Jadid", gendre: "Female"},
      {key: 7,name: "Abdelaziz Moha",pro: false,description: "En tant que plâtrier, mon travail consiste à appliquer du plâtre sur les murs, les plafonds et les autres surfaces intérieures pour créer une finition lisse et uniforme. Je suis responsable de la préparation des surfaces avant l'application du plâtre, notamment la pose des lattes de plâtre et la pose des bandes de jointoiement. Je suis également responsable de la découpe et de l'installation des plaques de plâtre et des panneaux de cloison sèche pour créer des murs et des plafonds lisses. Je travaille en étroite collaboration avec les clients et les autres professionnels de la construction pour répondre à leurs besoins en matière de texture et de finition de surface, tout en veillant à travailler en toute sécurité avec des outils électriques et des équipements potentiellement dangereux. La précision, la patience et la capacité à travailler en équipe sont des compétences clés pour réussir en tant que plâtrier.",rating: 88, star: 4,price: 300, job: "Plâtrier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104426585609740368/image.png",workImage: "",city: "Fès", gendre: "Male"},
      {key: 8,name: "Hassan Bouchaib",pro: false,description: "En tant que carreleur, mon travail consiste à poser des carreaux sur les sols, les murs et d'autres surfaces intérieures ou extérieures pour créer des finitions attrayantes et fonctionnelles. Je suis responsable de la préparation des surfaces avant la pose des carreaux, notamment la mise à niveau et le lissage des surfaces, ainsi que la découpe des carreaux pour les adapter aux dimensions requises. Je suis également responsable de la sélection et de la disposition des carreaux pour créer des motifs et des designs uniques. Je travaille en étroite collaboration avec les clients et les autres professionnels de la construction pour répondre à leurs besoins en matière de style et de fonctionnalité, tout en veillant à travailler en toute sécurité avec des outils électriques et des équipements potentiellement dangereux. La précision, la patience et la capacité à travailler en équipe sont des compétences clés pour réussir en tant que carreleur.",rating: 0, star: 0,price: 150, job: "Carreleur",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104426604307951636/image.png",workImage: "",city: "Marrakech", gendre: "Male"},
      {key: 9,name: "Karima Zaki",pro: false,description: "En tant qu'électricienne, mon travail consiste à installer, réparer et entretenir des systèmes électriques en toute sécurité. Je suis responsable de l'installation de nouveaux systèmes, de la réparation et de l'entretien des systèmes existants, ainsi que de la résolution de problèmes électriques. Je travaille avec des outils et des équipements spécialisés et je collabore étroitement avec les clients et les autres professionnels de la construction pour m'assurer que les systèmes électriques sont efficaces et fiables. La sécurité est une priorité absolue dans mon travail, car je travaille souvent avec des équipements électriques dangereux. Je dois également être en mesure de communiquer efficacement avec les autres membres de l'équipe de construction et de travailler en collaboration avec eux. La précision, la rigueur et la capacité à travailler sous pression sont des compétences clés pour réussir en tant qu'électricienne.",rating: 72, star: 3,price: 200, job: "Électricien",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104426761753735198/image.png",workImage: "",city: "Agadir", gendre: "Female"},
      {key: 10,name: "Ahmed Ben Ali",pro: false,description: "Un menuisier est un professionnel qui fabrique, installe et répare des structures en bois, en métal et en matériaux composites pour les bâtiments résidentiels, commerciaux et industriels. Ils travaillent à partir de plans et de dessins techniques pour créer des pièces sur mesure pour les portes, les fenêtres, les armoires, les meubles et les revêtements de sol. Les menuisiers utilisent une variété d'outils et d'équipements spécialisés pour couper, façonner et assembler les matériaux. La précision, l'attention aux détails et les compétences en mathématiques sont essentielles pour réussir en tant que menuisier.",rating: 94, star: 4,price: 400, job: "Menuisier",image: "",workImage: "",city: "Agadir", gendre: "Male"},
      {key: 11,name: "Sara El Amrani",pro: false,description: "Je suis une plombière professionnelle avec plus de 10 ans d’expérience dans l’installation, l’entretien et la réparation de systèmes de plomberie résidentiels et commerciaux. Je suis passionnée par mon travail et je m’efforce toujours de fournir un service de qualité à mes clients. Je suis également très fière d’être une femme dans un métier traditionnellement masculin.",rating: 81,star: 4,price: 350,job: "Plombier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1106994918557225131/image.png",workImage: "",city: "Casablanca", gendre: "Female"},
      {key: 12,name: "Mounir Chakir",pro: false,description: "Un peintre en bâtiment est un professionnel qui prépare, peint et décore les surfaces intérieures et extérieures des bâtiments résidentiels, commerciaux et industriels. Ils préparent les surfaces en nettoyant, en ponçant et en appliquant des apprêts pour s'assurer que la peinture adhère correctement. Les peintres utilisent une variété d'outils et d'équipements spécialisés pour appliquer la peinture, comme des pinceaux, des rouleaux et des pulvérisateurs. Ils peuvent également effectuer des travaux de décoration en appliquant des motifs ou des textures spécifiques. Les peintres travaillent souvent en équipe et peuvent collaborer avec d'autres professionnels de la construction pour s'assurer que les travaux sont effectués conformément aux normes de sécurité et de qualité. La précision, la patience et les compétences en communication sont essentielles pour réussir en tant que peintre en bâtiment.",rating: 90,star: 4,price: 400,job: "Peintre en bâtiment",image: "",workImage: "",city: "Rabat", gendre: "Male"},
      {key: 13,name: "Fouad El Houari",pro: false,description: "Un maçon est un professionnel de la construction qui travaille sur la construction, la réparation et l'entretien de structures telles que des murs, des bâtiments et des routes. Les maçons utilisent une variété de matériaux de construction tels que la brique, la pierre et le béton pour créer des structures solides et durables. Ils doivent être capables de lire des plans et de suivre des spécifications pour s'assurer que les structures sont construites selon les normes de sécurité et de qualité requises. Les tâches typiques d'un maçon comprennent la création de fondations, la construction de murs, la pose de briques, la réalisation de travaux de coffrage, le coulage de béton et l'installation de revêtements. Les maçons peuvent travailler sur des projets de construction résidentiels, commerciaux ou industriels, et travaillent souvent en collaboration avec d'autres professionnels de la construction pour s'assurer que le travail est effectué en temps voulu et selon les spécifications requises. La force physique, la précision et la dextérité manuelle sont des compétences importantes pour réussir en tant que maçon.",rating: 78,star: 4,price: 300,job: "Maçon",image: "",workImage: "",city: "Tangier", gendre: "Male"},
      {key: 14,name: "Amina Bensaid",pro: false,description: "Le couvreur est un professionnel qui travaille à la construction et à l'entretien des toitures pour les bâtiments résidentiels, commerciaux et industriels. Il travaille avec différents matériaux de toiture pour créer des toits durables et étanches. Les tâches incluent la préparation de la surface de la toiture, l'installation de matériaux de toiture, la réparation de fuites et l'entretien régulier des toits. La sécurité est une priorité absolue pour le couvreur, qui doit travailler en hauteur et utiliser des équipements de sécurité appropriés.",rating: 0,star: 0,price: 250,job: "Couvreur",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104426915886018780/image.png",workImage: "",city: "Marrakech", gendre: "Female"},
      {key: 15,name: "Abderrahim Zeroual",pro: true,description: "Un plâtrier est un professionnel spécialisé dans la préparation et la pose de matériaux de plâtrage pour les surfaces intérieures et extérieures des bâtiments. Il travaille avec différents types de plâtre, de mortier et de ciment pour créer des surfaces planes et lisses qui peuvent être peintes, tapissées ou décorées. Les tâches comprennent la préparation de la surface, l'application des matériaux de plâtrage, le lissage et le ponçage pour obtenir une finition parfaite. Le plâtrier peut également être impliqué dans des projets de rénovation pour réparer les murs endommagés ou les plafonds fissurés.",rating: 86,star: 4,price: 350,job: "Plâtrier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104427019107844257/image.png",workImage: "",city: "Agadir", gendre: "Male"},
      {key: 16,name: "Rachid El Moutaouakil",pro: true,description: "Un électricien est un professionnel qui installe, répare et entretient des systèmes électriques pour les bâtiments résidentiels, commerciaux et industriels. Ils ont une solide compréhension des principes électriques et des normes de sécurité. Leurs tâches comprennent l'installation de nouveaux systèmes électriques, la réparation et l'entretien des systèmes existants, la résolution de problèmes électriques et la communication avec les clients et les autres professionnels de la construction. La sécurité est primordiale pour les électriciens.",rating: 92,star: 5,price: 500,job: "Électricien",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104427136791621632/image.png",workImage: "",city: "Fès", gendre: "Male"},
      {key: 17,name: "Fatima Ezzahra",pro: true,description: "Un menuisier est un professionnel qui travaille avec le bois pour créer des meubles, des portes, des fenêtres, des escaliers et d'autres éléments architecturaux pour les bâtiments résidentiels, commerciaux et industriels. Ils utilisent une variété d'outils et de techniques pour mesurer, couper, façonner et assembler le bois, et sont également compétents dans l'utilisation de matériaux composites modernes. Les menuisiers ont une attention particulière aux détails et à la finition pour garantir que chaque élément qu'ils créent est fonctionnel, durable et esthétiquement agréable. Ils travaillent souvent en étroite collaboration avec les clients pour comprendre leurs besoins et créer des solutions sur mesure. La sécurité est également une préoccupation majeure pour les menuisiers, qui doivent respecter les normes de sécurité en utilisant des équipements de protection personnelle et en maintenant un environnement de travail sûr.",rating: 80,star: 4,price: 300,job: "Menuisier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104427230869868695/image.png",workImage: "",city: "Tangier", gendre: "Female"},
      {key: 18,name: "Hamza El Hadi",pro: true,description: "Le travail d'un plombier consiste à installer, réparer et entretenir des systèmes de plomberie pour les bâtiments résidentiels, commerciaux et industriels. Les plombiers sont des professionnels hautement qualifiés qui ont une solide compréhension des principes de la plomberie et des normes de sécurité. Leurs tâches comprennent l'installation de nouveaux systèmes de plomberie, la réparation et l'entretien des systèmes existants, la résolution de problèmes de plomberie et la communication avec les clients et les autres professionnels de la construction. La sécurité est primordiale pour les plombiers.",rating: 85,star: 4,price: 350,job: "Plombier",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104427338587967549/image.png",workImage: "",city: "Meknès", gendre: "Male"},
      {key: 19,name: "Nawal Bouhssine",pro: true,description: "Un peintre en bâtiment est un professionnel qui se spécialise dans la peinture et la décoration d'intérieurs et d'extérieurs de bâtiments résidentiels, commerciaux et industriels. Leur travail consiste à préparer les surfaces à peindre, appliquer les couches de peinture ou de revêtements nécessaires, et assurer un résultat final de haute qualité. Ils utilisent des outils spécialisés tels que des pinceaux, des rouleaux, des pistolets de pulvérisation, et travaillent en étroite collaboration avec les clients pour répondre à leurs besoins esthétiques. La sécurité est également une priorité pour les peintres en bâtiment, qui doivent souvent travailler en hauteur et manipuler des produits chimiques potentiellement dangereux.",rating: 79,star: 4,price: 400,job: "Peintre en bâtiment",image: "https://cdn.discordapp.com/attachments/589338815869747203/1104427513003921479/image.png",workImage: "",city: "Casablanca", gendre: "Female"},
      
    ]

        
        const specificItem = khedama.find(item => item.key == workerId);

       
    const handlealert = () => {
      alert("hehehe")
    }
   return (
    <>
   <div className='flex flex-col gap-6 justify-center items-center'>
    
          <div className='w-[80%] h-[700px]  bg-white flex rounded-md border-2 border-gray-500' >
              <div className='w-[50%] h-full  p-4 lg:flex hidden'>
              <img className='h-full w-full object-cover rounded-md' src="https://cdn.discordapp.com/attachments/589338815869747203/1106996068702507140/image.png" alt="" />
              </div>
              <div className=' h-full p-4 lg:w-[50%] w-[100%]'>
                <div className='w-full h-full bg-white rounded-md flex flex-col '>
                      <div className='w-full h-[40%]  flex  border-b-4'>
                              <div className='w-[40%] h-full  flex justify-center items-center'>
                                <div className='w-[80%] h-[80%] bg-red-500 rounded-full'>
                                      <img className=' object-cover h-full w-full rounded-full' src={specificItem.image} alt="" /> 
                                </div>
                              </div>
                              <div className='w-[60%] h-full  px-4 text-start flex flex-col justify-center'>
                                <div className='flex flex-col'>
                                    <p className='text-[40px] text-black'>{specificItem.name}</p>
                                    <p className='text-[25px] text-black '>{specificItem.job}</p>
                                </div>
                                    <div className='flex items-center gap-2 text-[20px]'><span className='text-[20px] font-bold'>Rating:</span> <p>{Array(specificItem.star).fill('⭐️').join('')}({specificItem.rating}) </p></div>
                                    
                              </div>
                      </div>
                      <div className='w-full h-[60%] bg-white p-8  flex flex-col'>

                        <div>
                          <h1 className='text-[25px] font-bold mb-2'>Description :</h1>
                          
                          <p className='text-[16px]'>{specificItem.description}</p>
                        </div>

                        <div className='mt-auto flex gap-6 justify-center'>
                          <button onClick={handlealert} className='w-[40%] h-[50px] bg-green-500 rounded-md text-white font-bold text-[17px] hover:brightness-90 transition-all ease-linear'>Hire Me</button> 
                          <button className='w-[40%] h-[50px] border-2 border-green-500 rounded-md text-black font-bold text-[17px] flex items-center justify-center gap-4 hover:bg-green-500 hover:text-white transition-all duration-300 ease-in'> <BsChatDots size={23} /> Contact Me</button> 
                          
                        </div>

                      </div>
                </div>
                  
              </div>
          </div>



          <div className='w-[80%] h-auto rounded-lg p-6 flex flx-col flex-wrap  gap-2 '> 
            <h1 className='text-white text-[40px] text-bold '>Reviews</h1>
            <div className='w-[100%] h-1 bg-gray-300 mb-5' />
              <div className='flex flex-wrap  gap-2'>
              {khedama.slice(0,1).map((test) =>
                <Reviews />
              )}
              </div>
                    
              
    


        </div>
    </div>
    </>
  )
}
